Adds extra kops cluster.spec config before creating cluster

diff --git a/roles/kubernetes_cluster/tasks/delete_cluster.yaml b/roles/kubernetes_cluster/tasks/delete_cluster.yaml
--- a/roles/kubernetes_cluster/tasks/delete_cluster.yaml
+++ b/roles/kubernetes_cluster/tasks/delete_cluster.yaml
@@ -2,22 +2,21 @@
 - name: Delete Cluster
   register: result
   changed_when: result.rc == 101
-  failed_when: (result.rc != 100) and (result.rc != 101)
+  failed_when: result.rc not in [100, 101]
   shell: |
     kops get cluster \
-        --name {{ cluster_fqdn }} \
-        --state s3://{{ kubernetes_cluster.state_bucket }}/{{ cluster_fqdn }}/kops
+      --name {{ cluster_fqdn }} \
+      --state s3://{{ kubernetes_cluster.state_bucket }}/{{ cluster_fqdn }}/kops
+    if [[ $? -eq 1 ]]; then { exit 100; } fi
 
-    if [[ $? -eq 0 ]]; then
-      kops delete cluster \
-        --name="{{ cluster_fqdn }}" \
-        --state="s3://{{ kubernetes_cluster.state_bucket }}/{{ cluster_fqdn }}/kops" \
-        --yes
-      if [ $? -ne 0 ]; then { echo "Failed to delete cluster"; exit 1; } fi
-      exit 101
-    fi
+    kops delete cluster \
+      --name="{{ cluster_fqdn }}" \
+      --state="s3://{{ kubernetes_cluster.state_bucket }}/{{ cluster_fqdn }}/kops" \
+      --yes
+    if [ $? -eq 0 ]; then { exit 101; } fi
 
-    exit 100
+    echo "Failed to delete cluster"
+    exit 1
 
 - name: Delete kOps S3 Bucket
   amazon.aws.aws_s3:
